blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='index'),

    path('<int:pk>/', views.PostDetail.as_view()),

    path('categoryblog/<str:slug>/', views.categoryblog_page),

    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),

    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),

    path('<int:pk>/new_feedback/', views.new_feedback),
    path('update_feedback/<int:pk>/', views.FeedbackUpdate.as_view()),
    path('delete_feedback/<int:pk>/', views.delete_feedback),

    path('search/<str:q>/', views.PostSearch.as_view()),
]

boards/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'boards'

urlpatterns = [


    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('<str:category_name>/', base_views.index, name='index'),

    # question_views.py
    path('question/create/<str:category_name>/', question_views.question_create, name='question_create'),
    #path('question/create/', question_views.question_create, name='question_create'),


    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    #about voter
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]

"""

    ################
    # base_views.py
    path('question/list/', base_views.index, name='index'),
    path('question/list/<str:category_name>/', base_views.index, name='index'),
    path('question/detail/<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/<str:category_name>/', question_views.question_create, name='question_create'),
    ################     
"""

"""

    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),

"""

config/urls.py
from django.contrib import admin
from django.urls import path, include
from boards.views import base_views

from django.conf import settings
from django.conf.urls.static import static

from .settings import base


urlpatterns = [
    path('memo/', include('memo.urls')),
    path('profilehistory/', include('profilehistory.urls')),
    path('accounts/', include('allauth.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('common/', include('common.urls')),
    path('', include('single_pages.urls')),
]

#    path('', base_views.index, name='index'),  # '/' 에 해당되는 path

handler404 = 'common.views.page_not_found'
handler413 = 'common.views.request_entity_too_large'
handler500 = 'common.views.internal_server_error'
handler502 = 'common.views.bad_gateway'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

profilehistory/urls.py
from django.urls import path
from . import views

app_name = 'profilehistory'

urlpatterns = [
    path('', views.ProfileList.as_view(), name='index'),
    path('<int:pk>/', views.ProfileDetail.as_view(), name='detail'),
    path('create/', views.ProfileCreate.as_view(), name='profile_create'),
    path('<str:userid>/', views.profile_find, name='profile_find'),

]

boards/models.py
from django.db import models
from django.contrib.auth.models import User
import os
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    has_answer = models.BooleanField(default=True)  # 답변가능 여부

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('boards:index', args=[self.name])

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, null=True, blank=True, related_name='voter_question')  # 추천인 추가

    head_image = models.ImageField(upload_to='boards/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='boards/files/%Y/%m/%d/', blank=True)

    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_question')

    def __str__(self):
        return self.subject

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]


    def get_absolute_url(self):
        return f'/boards/{self.pk}'

#    def get_absolute_url(self):
#        return reverse('boards:question_detail', args=[self.id])

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

boards/forms.py
from django import forms
from boards.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content', 'head_image', 'file_upload']  # QuestionForm에서 사용할 Question 모델의 속성
        """
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        """
        labels = {
            'subject': '제목',
            'content': '내용',
            'head_image': '이미지',
            'file_upload': '파일',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post, Categoryblog, Comment, Feedback
from django.shortcuts import get_object_or_404

from django.core.exceptions import PermissionDenied

from .forms import CommentForm, FeedbackForm
from django.db.models import Q

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'head_image', 'file_upload', 'categoryblog']

    template_name = 'blog/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'head_image', 'file_upload', 'categoryblog']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect('/blog/')

class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categoriesblog'] = Categoryblog.objects.all()
        context['no_categoryblog_post_count'] = Post.objects.filter(categoryblog=None).count()
        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categoriesblog'] = Categoryblog.objects.all()
        context['no_categoryblog_post_count'] = Post.objects.filter(categoryblog=None).count()
        context['comment_form'] = CommentForm
        context['feedback_Form'] = FeedbackForm
        return context

def categoryblog_page(request, slug):
    print('slug!!!!!!!!!!!!!!!!!',slug)
    if slug == 'no_category':
        categoryblog = '미분류'
        post_list = Post.objects.filter(categoryblog=None)
    else:
        categoryblog = Categoryblog.objects.get(slug=slug)
        post_list = Post.objects.filter(categoryblog=categoryblog)

    return render(
        request,
        'blog/post_list.html',
        {
            'post_list': post_list,
            'categoriesblog': Categoryblog.objects.all(),
            'no_categoryblog_post_count': Post.objects.filter(categoryblog=None).count(),
            'categoryblog': categoryblog,
        }
    )


def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post

    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q) | Q(content__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'

        return context



def new_feedback(request, pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=pk)

        if request.method == 'POST':
            feedback_form = FeedbackForm(request.POST)
            if feedback_form.is_valid():
                feedback = feedback_form.save(commit=False)
                feedback.comment = comment
                feedback.author = request.user
                feedback.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(comment.get_absolute_url())
    else:
        raise PermissionDenied



class FeedbackUpdate(LoginRequiredMixin, UpdateView):
    model = Feedback
    form_class = FeedbackForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(FeedbackUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


def delete_feedback(request, pk):
    feedback = get_object_or_404(Feedback, pk=pk)
    comment = feedback.comment

    if request.user.is_authenticated and request.user == feedback.author:
        feedback.delete()
        return redirect(comment.get_absolute_url())
    else:
        raise PermissionDenied

boards/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer



@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('boards:detail', question_id=question.id), answer.id))
    else:
            form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'boards/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('boards:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('boards:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'boards/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('boards:detail', question_id=answer.question.id)

@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 댓글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(
                resolve_url('boards:detail', question_id=answer.question.id), answer.id))

boards/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.db.models import Count
from ..models import Question, Category


def index(request, category_name='notice'):
    #3/0
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    category_list = Category.objects.all()
    category = get_object_or_404(Category, name=category_name)
    question_list = Question.objects.filter(category=category)

    # 정렬
    if so == 'recommend':
        # aggretation, annotation에는 relationship에 대한 역방향 참조도 가능 (ex. Count('voter'))
        question_list = question_list.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = question_list.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = question_list.order_by('-create_date')

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 질문 제목검색
            Q(content__icontains=kw) |  # 질문 내용검색
            Q(answer__content__icontains=kw) |  # 답변 내용검색
            Q(author__username__icontains=kw) |  # 질문 작성자검색
            Q(answer__author__username__icontains=kw)  # 답변 작성자검색
        ).distinct()

    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    """
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    """

    max_index = len(paginator.page_range)

    context = {'question_list': page_obj, 'max_index': max_index, 'page': page, 'kw': kw, 'so': so,
               'category_list': category_list, 'category': category}

    return render(request, 'boards/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'boards/question_detail.html', context)

templates/boards/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-success">저장하기</button>
    </form>

</div>
{% endblock %}

templates/boards/question_detail.html
{% extends 'base.html' %}
{% load boards_filter %}

{% block head_title %}
    {{ question.subject }} - Post
{% endblock %}

{% block content %}

<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->

    <h2 class="border-bottom py-2">{{ question.subject }}</h2>

    <div class="card my-3">
        <div class="card-body">
                        {% if question.head_image %}
                            <figure class="mb-4"><img class="card-img-top" src="{{ question.head_image.url }}" alt="{{ post }} head image" /></figure>
                        {% else %}
                            <figure class="mb-4"><img class="card-img-top" src="/static/images/logo.jpg" alt="{{ post }} head image" /></figure>

                        {% endif %}

            <div class="card-text" >{{ question.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ question.modify_date }}</div>
                    </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                        <div class="mb-2"><a href="{% url 'profilehistory:profile_find' question.author %}">{{ question.author.username }}</a></div>
                        <div>{{ question.create_date }}</div>
                </div>
            </div>

            <div class="my-3">

                <a href="javascript:void(0)" data-uri="{% url 'boards:question_vote' question.id  %}"
               class="recommend btn btn-sm btn-outline-secondary"> 추천
                <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
                </a>

                {% if request.user == question.author %}
                <a href="{% url 'boards:question_modify' question.id  %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'boards:question_delete' question.id  %}">삭제</a>
                {% endif %}
             </div>
             <div class="my-3">
                 {% if question.file_upload %}
                <a href="{{ question.file_upload.url }}" class="btn btn-sm float-end btn-outline-secondary " role="button" download>
                    Download : {{ question.get_file_name }}
                </a>
                {% endif %}

            </div>

        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ answer.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ answer.modify_date }}</div>
                    </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2"><a href="{% url 'profilehistory:profile_find' answer.author %}">{{ answer.author.username }}</a></div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{% url 'boards:answer_vote' answer.id  %}"
               class="recommend btn btn-sm btn-outline-secondary"> 추천
                <span class="badge rounded-pill bg-success">{{answer.voter.count}}</span>
                </a>

            {% if request.user == answer.author %}
            <a href="{% url 'boards:answer_modify' answer.id  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{% url 'boards:answer_delete' answer.id  %}">삭제</a>
            {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'boards:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
                <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div class="mb-3">
            <label for="content" class="form-label">답변!내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10">
            </textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-success">

    </form>

</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});

const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});

</script>
{% endblock %}

templates/boards/question_list.html
{% extends 'base.html' %}
{% load boards_filter %}
{% block content %}

<div class="container my-3">
    <div class="row my-3">
        <div class="col-6"><!-- comment -->


            {% if user.is_authenticated%}
                {% if category.description == '공지사항' %}
                    {% if user.is_superuser or user.is_staff %}
                        <a href="{% url 'boards:question_create' category %}" class="btn btn-success">{{ category.description }} 글 등록하기</a>
                    {% else %}

                    {% endif %}
                {% else %}
                    <a href="{% url 'boards:question_create' category %}" class="btn btn-success">{{ category.description }} - 글 등록하기</a>
                {% endif %}

            {% else %}

            {% endif %}

        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>


<ul class="nav nav-tabs">
        {% for cat in category_list %}
            {% if cat == category %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ cat.get_absolute_url }}">{{ cat.description }} / </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ cat.get_absolute_url }}">{{ cat.description }} / </a>
                </li>
            {% endif %}
        {% endfor %}
</ul>


 <table class="table" style="font-size: 12px">
        <thead>
            <tr class="text-center table-dark">
                <th>#</th>
                    <th style="width:50px">Himg</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>

        {% if question_list %}
            {% for question in question_list %}


                    {% if category.description == question.category.description %}
                    <tr class="text-center">

                        <td>
                            <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                            {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                        </td>
                        <td>

                            {% if question.head_image %}
                                <figure class="mb-4"><img class="card-img-top" src="{{ question.head_image.url }}" alt="{{ post }} head image" width="40" height="30" /></figure>
                            {% else %}
                                <figure class="mb-4"><img class="card-img-top" src="/static/images/logo.jpg" alt="{{ post }} head image"  width="40" height="30"/></figure>
                            {% endif %}

                        </td>
                        <td class="text-start" style="font-size: 20px">
                            ( {{question.voter.count}} )

                            <a href="{% url 'boards:detail' question.id %}">{{ question.subject }}</a>
                            {% if question.answer_set.count > 0 %}
                             <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>

                            {% endif %}

                        </td>


                        <td><a href="{% url 'profilehistory:profile_find' question.author %}">{{ question.author.username }}</a></td>  <!-- 글쓴이 추가 -->
                        <td class="text-start">
                            {{ question.create_date | date:'Y-m-d H:i:s' }}
                        </td>


                    </tr>

                    {% endif %}
            {% endfor %}
        {% else %}
        <tr>
            <td colspan="5">글이 없습니다.</td>
        </tr>
        {% endif %}

        </tbody>
    </table>

        <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
           href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
               href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
           href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'boards:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}