blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='index'),

    path('<int:pk>/', views.PostDetail.as_view()),

    path('categoryblog/<str:slug>/', views.categoryblog_page),

    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),

    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),

    path('<int:pk>/new_feedback/', views.new_feedback),
    path('update_feedback/<int:pk>/', views.FeedbackUpdate.as_view()),
    path('delete_feedback/<int:pk>/', views.delete_feedback),

    path('search/<str:q>/', views.PostSearch.as_view()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from boards.views import base_views

from django.conf import settings
from django.conf.urls.static import static

from .settings import base


urlpatterns = [
    path('memo/', include('memo.urls')),
    path('profilehistory/', include('profilehistory.urls')),
    path('accounts/', include('allauth.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('common/', include('common.urls')),
    path('', include('single_pages.urls')),
]

#    path('', base_views.index, name='index'),  # '/' 에 해당되는 path

handler404 = 'common.views.page_not_found'
handler413 = 'common.views.request_entity_too_large'
handler500 = 'common.views.internal_server_error'
handler502 = 'common.views.bad_gateway'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

profilehistory/urls.py
from django.urls import path
from . import views

app_name = 'profilehistory'

urlpatterns = [
    path('', views.ProfileList.as_view(), name='index'),
    path('<int:pk>/', views.ProfileDetail.as_view(), name='detail'),
    path('create/', views.ProfileCreate.as_view(), name='profile_create'),
    path('<str:userid>/', views.profile_find, name='profile_find'),

]

blog/models.py
from django.db import models
import os
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown

# Create your models here.

class Categoryblog(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog/categoryblog/{self.slug}/'


    class Meta:
        verbose_name_plural = 'categoriesblog'


class Post(models.Model):
    title = models.CharField(max_length=30)
    content = MarkdownxField()#models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    categoryblog = models.ForeignKey(Categoryblog, null=True, blank=True, on_delete=models.SET_NULL)


    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/blog/{self.pk}'

    def get_file_name(self):
        return os.path.basename(self.file_upload.name)

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1]

    def get_content_markdown(self):
        return markdown(self.content)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

class Feedback(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    content = MarkdownxField()#models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        #return f''
        return f'{self.comment.get_absolute_url()}#feedback-{self.pk}'


    def get_content_markdown(self):
        return markdown(self.content)


"""
    def get_absolute_url(self):
        return f'{self.comment.get_absolute_url()}#feedback-{self.pk}'
"""

blog/forms.py
from .models import Comment, Feedback
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ('content',)

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post, Categoryblog, Comment, Feedback
from django.shortcuts import get_object_or_404

from django.core.exceptions import PermissionDenied

from .forms import CommentForm, FeedbackForm
from django.db.models import Q

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'head_image', 'file_upload', 'categoryblog']

    template_name = 'blog/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'head_image', 'file_upload', 'categoryblog']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect('/blog/')

class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categoriesblog'] = Categoryblog.objects.all()
        context['no_categoryblog_post_count'] = Post.objects.filter(categoryblog=None).count()
        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categoriesblog'] = Categoryblog.objects.all()
        context['no_categoryblog_post_count'] = Post.objects.filter(categoryblog=None).count()
        context['comment_form'] = CommentForm
        context['feedback_Form'] = FeedbackForm
        return context

def categoryblog_page(request, slug):
    print('slug!!!!!!!!!!!!!!!!!',slug)
    if slug == 'no_category':
        categoryblog = '미분류'
        post_list = Post.objects.filter(categoryblog=None)
    else:
        categoryblog = Categoryblog.objects.get(slug=slug)
        post_list = Post.objects.filter(categoryblog=categoryblog)

    return render(
        request,
        'blog/post_list.html',
        {
            'post_list': post_list,
            'categoriesblog': Categoryblog.objects.all(),
            'no_categoryblog_post_count': Post.objects.filter(categoryblog=None).count(),
            'categoryblog': categoryblog,
        }
    )


def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied


class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post

    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q) | Q(content__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'

        return context



def new_feedback(request, pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=pk)

        if request.method == 'POST':
            feedback_form = FeedbackForm(request.POST)
            if feedback_form.is_valid():
                feedback = feedback_form.save(commit=False)
                feedback.comment = comment
                feedback.author = request.user
                feedback.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(comment.get_absolute_url())
    else:
        raise PermissionDenied



class FeedbackUpdate(LoginRequiredMixin, UpdateView):
    model = Feedback
    form_class = FeedbackForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(FeedbackUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


def delete_feedback(request, pk):
    feedback = get_object_or_404(Feedback, pk=pk)
    comment = feedback.comment

    if request.user.is_authenticated and request.user == feedback.author:
        feedback.delete()
        return redirect(comment.get_absolute_url())
    else:
        raise PermissionDenied

templates/blog/comment_form.html
{% extends 'base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Edit Comment - Blog{% endblock %}

{% block content %}
    <h1>Edit Comment</h1>
    <hr/>
    <form method="post" id="comment-form">{% csrf_token %}
        {{ form | crispy }}
        <br/>
        <button type="submit" class="btn btn-success float-end">Submit</button>
    </form>
{% endblock %}

templates/blog/feedback_form.html
{% extends 'base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Edit Feedback - Blog{% endblock %}

{% block content %}
    <h1>Edit Feedback</h1>
    <hr/>
    <form method="post" id="feedback-form">{% csrf_token %}
        {{ form | crispy }}
        <br/>
        <button type="submit" class="btn btn-success float-end">Submit</button>
    </form>
{% endblock %}

templates/blog/post_form.html
{% extends 'base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Create Post - Blog{% endblock %}

{% block content %}
    <h1>Create New Post</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form | crispy }}
        </table>

        <br/>

        <button type="submit" class="btn btn-success float-end">Submit</button>
    </form>
    {{ form.media }}
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}
{% load boards_filter %}
{% block content %}

    <!-- Page content-->
        <div class="container">
            <div class="row">




                <!-- Blog entries-->
                <div class="col-lg-8">
                    <div>

                        {% if user.is_authenticated%}
                            {% if user.is_superuser or user.is_staff %}
                                <a class="btn btn-success float-end" href="/blog/create_post/" role="button">New Post</a>
                            {% endif %}
                        {% endif %}

                        <h1>Blog
                            {% if search_info %} : <small class="text-muted">{{ search_info }}</small>{% endif %}
                            {% if categoryblog %} : <span class="badge bg-secondary">{{ categoryblog }}</span>{% endif %}
                        </h1>

                    </div>
                    {% if post_list.exists %}
                    {% for p in post_list %}
                    <!-- blog post-->
                    <div class="card mb-4" id="post-{{ p.pk }}">
                        {% if p.head_image %}
                            <img class="card-img-top" src="{{ p.head_image.url }}" alt="{{ p }} head image" />
                        {% else %}
                            <img class="card-img-top" src="/static/images/logo.jpg" alt="{{ p }} head image" />
                        {% endif %}

                        <div class="card-body">

                            {% if p.categoryblog %}

                                <span class="badge bg-secondary float-right">{{ p.categoryblog }}</span>
                            {% else %}

                                <span class="badge bg-secondary float-right">미분류</span>
                            {% endif %}

                            <h2 class="card-title">{{ p.title }}</h2>
                            <p class="card-text">{{ p.get_content_markdown | truncatewords_html:30 | safe }}</p>
                            <a class="btn btn-success" href="{{ p.get_absolute_url }}">Read more →</a>
                        </div>

                        <div class="card-footer text-muted">
                            Posted on {{ p.created_at }} by <a href="{% url 'profilehistory:profile_find' p.author %}">{{ p.author }}</a>
                        </div>
                    </div>
                        {% endfor %}
                    {% else %}
                    not yet
                    {% endif %}


                    <!--pagination-->
                    {% if is_paginated %}
                        <!-- Pagination -->
                        <ul class="pagination justify-content-center mb-4">
                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&larr; Older</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link" href="#">&larr; Older</a>
                                </li>
                            {% endif %}

                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Newer &rarr;</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link" href="#">Newer &rarr;</a>
                                </li>
                            {% endif %}
                        </ul>
                    {% endif %}



                </div>

                <!-- Side widgets-->
                            <div class="col-lg-4">
                                <!-- Search widget-->
                                <div class="card mb-4">
                                    <div class="card-header">Search</div>
                                    <div class="card-body">
                                        <div class="input-group">
                                            <input type="text" class="form-control" placeholder="Search for..." id="search-input">
                                            <span class="input-group-btn">
                                                    <button class="btn btn-secondary" type="button" onclick="searchPost();">Go!</button>
                                                </span>
                                    </div>
                                    </div>
                                </div>
                                <!-- Categories widget-->
                                <div class="card my-4" id="categories-card">
                                    <h5 class="card-header">총 {{ categoriesblog.count }} 개의 카테고리</h5>
                                    <div class="card-body">
                                        <div class="row">
                                                        {% for category in categoriesblog %}
                                                        <li>
                                                            <a href="{{ category.get_absolute_url }}">{{ category }} ({{ category.post_set.count }})</a>
                                                        </li>
                                                        {% endfor %}
                                                        <li>
                                                            <a href="/blog/categoryblog/no_category/">미분류 ({{ no_categoryblog_post_count }})</a>
                                                        </li>
                                        </div>
                                    </div>
                                </div>
                            </div>

            </div>
        </div>


{% endblock %}

templates/blog/post_update_form.html
{% extends 'base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Edit Post - Blog{% endblock %}

{% block content %}
    <h1>Edit New Post</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form | crispy }}
        </table>

        <br/>

        <button type="submit" class="btn btn-success float-right">Submit</button>
    </form>
    {{ form.media }}
{% endblock %}