blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='index'),

    path('<int:pk>/', views.PostDetail.as_view()),

    path('categoryblog/<str:slug>/', views.categoryblog_page),

    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),

    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),

    path('<int:pk>/new_feedback/', views.new_feedback),
    path('update_feedback/<int:pk>/', views.FeedbackUpdate.as_view()),
    path('delete_feedback/<int:pk>/', views.delete_feedback),

    path('search/<str:q>/', views.PostSearch.as_view()),
]

boards/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'boards'

urlpatterns = [


    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('<str:category_name>/', base_views.index, name='index'),

    # question_views.py
    path('question/create/<str:category_name>/', question_views.question_create, name='question_create'),
    #path('question/create/', question_views.question_create, name='question_create'),


    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    #about voter
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]

"""

    ################
    # base_views.py
    path('question/list/', base_views.index, name='index'),
    path('question/list/<str:category_name>/', base_views.index, name='index'),
    path('question/detail/<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/<str:category_name>/', question_views.question_create, name='question_create'),
    ################     
"""

"""

    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),

"""

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from boards.views import base_views

from django.conf import settings
from django.conf.urls.static import static

from .settings import base


urlpatterns = [
    path('memo/', include('memo.urls')),
    path('profilehistory/', include('profilehistory.urls')),
    path('accounts/', include('allauth.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('common/', include('common.urls')),
    path('', include('single_pages.urls')),
]

#    path('', base_views.index, name='index'),  # '/' 에 해당되는 path

handler404 = 'common.views.page_not_found'
handler413 = 'common.views.request_entity_too_large'
handler500 = 'common.views.internal_server_error'
handler502 = 'common.views.bad_gateway'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

profilehistory/urls.py
from django.urls import path
from . import views

app_name = 'profilehistory'

urlpatterns = [
    path('', views.ProfileList.as_view(), name='index'),
    path('<int:pk>/', views.ProfileDetail.as_view(), name='detail'),
    path('create/', views.ProfileCreate.as_view(), name='profile_create'),
    path('<str:userid>/', views.profile_find, name='profile_find'),

]

single_pages/urls.py
from django.urls import path
from . import views

app_name = 'single_pages'

urlpatterns = [
    path('about_us/', views.about_us),
    path('', views.landing, name='index'),
]

boards/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.db.models import Count
from ..models import Question, Category


def index(request, category_name='notice'):
    #3/0
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    category_list = Category.objects.all()
    category = get_object_or_404(Category, name=category_name)
    question_list = Question.objects.filter(category=category)

    # 정렬
    if so == 'recommend':
        # aggretation, annotation에는 relationship에 대한 역방향 참조도 가능 (ex. Count('voter'))
        question_list = question_list.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = question_list.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = question_list.order_by('-create_date')

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 질문 제목검색
            Q(content__icontains=kw) |  # 질문 내용검색
            Q(answer__content__icontains=kw) |  # 답변 내용검색
            Q(author__username__icontains=kw) |  # 질문 작성자검색
            Q(answer__author__username__icontains=kw)  # 답변 작성자검색
        ).distinct()

    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    """
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    """

    max_index = len(paginator.page_range)

    context = {'question_list': page_obj, 'max_index': max_index, 'page': page, 'kw': kw, 'so': so,
               'category_list': category_list, 'category': category}

    return render(request, 'boards/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'boards/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- post CSS -->
    <link rel="stylesheet" href="{% static 'blog-post.css' %}" media="screen">



    {% block css %}
    {% endblock %}

    <title>
        {% block head_title %}
            codingcity.net
        {% endblock %}
    </title>

</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->



<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

<script>
    function searchPost(){
        let searchValue = document.getElementById('search-input').value.trim();
        if (searchValue.length > 1){
            location.href="/blog/search/" + searchValue + "/";
        }
        else{
            alert('검색어('+ searchValue +')가 너무 짧습니다.');
        }
    };

    document.getElementById('search-input').addEventListener('keyup', function(event){
        if(event.key === 'Enter'){
            searchPost();
        }
    });
</script>

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
{% include 'footer.html' %}
</body>
</html>

templates/base_full_width.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- post CSS -->
    <link rel="stylesheet" href="{% static 'blog-post.css' %}" media="screen">

    <title>{% block head_title %}codingcity.net{% endblock %}</title>

</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
{% include 'footer.html' %}
</body>
</html>

templates/footer.html
        <!-- Footer-->
        <footer class="pt-0 bg-dark fixed-bottom">
            <div class="container">
                <p class="m-0 text-center text-white">
                    Copyright &copy; codingcity.net 2023
                </p>
            </div>
        </footer>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'single_pages:index' %}">
            <img class="img-fluid rounded" src="/static/images/logo.png"  alt="logos" width="89" height="42" >
            codingcity.net
        </a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:index' %}">강의블로그</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'boards:index' %}">자유게시판</a>
                </li>


                {% if user.is_authenticated %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">마이페이지</a>
                    <ul class="dropdown-menu">
                            {% if user.is_authenticated %}
                            <li>
                                    <a class="dropdown-item" href="{% url 'profilehistory:index' %}">{{ user.username }}'s 프로필</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="/memo/">{{ user.username }}'s memoBox</a>
                            </li>
                            <li>
                                    <a class="dropdown-item" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                            </li>

                            {% endif %}




                        {% if user.is_authenticated and user.is_staff %}

                          <li><hr class="dropdown-divider"></li>

                        <li>
                                <a class="dropdown-item" href="/admin" target='_blank'>관리자페이지</a>
                        </li>
                        {% endif %}

                    </ul>
                  </li>
                {% else %}
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>

                </li>
                {% endif %}



            <!--
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
            -->



                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>

            </ul>
        </div>
    </div>
</nav>