blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='index'),

    path('<int:pk>/', views.PostDetail.as_view()),

    path('categoryblog/<str:slug>/', views.categoryblog_page),

    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),

    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),

    path('<int:pk>/new_feedback/', views.new_feedback),
    path('update_feedback/<int:pk>/', views.FeedbackUpdate.as_view()),
    path('delete_feedback/<int:pk>/', views.delete_feedback),

    path('search/<str:q>/', views.PostSearch.as_view()),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from boards.views import base_views

from django.conf import settings
from django.conf.urls.static import static

from .settings import base


urlpatterns = [
    path('memo/', include('memo.urls')),
    path('profilehistory/', include('profilehistory.urls')),
    path('accounts/', include('allauth.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('common/', include('common.urls')),
    path('', include('single_pages.urls')),
]

#    path('', base_views.index, name='index'),  # '/' 에 해당되는 path

handler404 = 'common.views.page_not_found'
handler413 = 'common.views.request_entity_too_large'
handler500 = 'common.views.internal_server_error'
handler502 = 'common.views.bad_gateway'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

profilehistory/urls.py
from django.urls import path
from . import views

app_name = 'profilehistory'

urlpatterns = [
    path('', views.ProfileList.as_view(), name='index'),
    path('<int:pk>/', views.ProfileDetail.as_view(), name='detail'),
    path('create/', views.ProfileCreate.as_view(), name='profile_create'),
    path('<str:userid>/', views.profile_find, name='profile_find'),

]

profilehistory/models.py
from django.db import models

# Create your models here.

#for profile
from django.contrib.auth.models import User



class Profile(models.Model):
    thisuser = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_profile')
    user_image = models.ImageField(upload_to='profile/images/%Y/%m/%d/', blank=True)
    intro = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)

    public_approved = models.BooleanField(default=False)
    birthdate = models.DateField(null=True)

    def __str__(self):
        return f'[{self.pk}] {self.thisuser} : {self.intro}'

    def get_absolute_url(self):
        return f'/profilehistory/{self.pk}'

    #birthday = models.DateField(auto_now=False)

    #modify_date = models.DateTimeField(null=True, blank=True) #no #그냥 매번 프로필 만들고, 수정없슴 걍 최근꺼 보여주기, 기록남겨서 개인히스토리
    #nickname = models.CharField(max_length=10)

    #def __str__(self):
    #    return self.nickname

profilehistory/forms.py
from django import forms
from profilehistory.models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile  # 사용할 모델
        fields = ['user_image', 'intro', 'public_approved', 'birthdate']

        labels = {
            'user_image': '대표 이미지',
            'intro': '자기소개',
            'public_approved': '프로필 공개여부',
            'birthdate': '생년월일',
        }

profilehistory/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView
from .models import Profile
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied

from django.contrib.auth.models import User

# Create your views here.





class ProfileList(ListView):
    model = Profile
    ordering = '-pk'

class ProfileDetail(DetailView):#,UserPassesTestMixin,LoginRequiredMixin,
    model = Profile

    def test_func(self):
        return self.request.user.is_authenticated

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.thisuser = current_user
            response = super(ProfileCreate, self).form_valid(form)

            return response
        else:
            return redirect('/profileHistory/')

class ProfileCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Profile
    fields = ['user_image', 'intro', 'public_approved', 'birthdate']#, 'created_at','thisuser']

    def test_func(self):
        return self.request.user.is_authenticated

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.thisuser = current_user
            response = super(ProfileCreate, self).form_valid(form)

            return response
        else:
            return redirect('/profileHistory/')



def profile_find(request, userid):

    """
    print('????????????userid',userid)
    info1 =User.objects.get(username=userid)
    print('???????????!!!!?info1', info1)

    info = Profile.objects.get(public_approved=True, thisuser=info1)
    print('!!!!!!!!!!!!!!!!',info)
    profile_list = Profile.objects.filter(thisuser=info)

    profile_list = Profile.objects.get(public_approved=True)
    print('!!!!!!!!!!!!!!!!',profile_list)


    info = get_object_or_404(Profile, userid=userid)
    print('!!!!!!!!!!!!!!!!', info)
    profile_list = Profile.objects.filter(thisuser=info)

    print('!!!!!!!!!!!!!!!!', userid)
    username = User.objects.filter(id=userid)

    """
    username = User.objects.get(username=userid)
    print('!!!!!!!!!!!!!!!!', username.id)


    profile_list = Profile.objects.filter(thisuser=username.id )
    print('!!!!!!!!!!!!!!!!', profile_list)


    profile_list = Profile.objects.filter(public_approved=True) & Profile.objects.filter(thisuser=username.id )
    print('!!!!!!!!!!!!!!!!', profile_list)

    is_userid = True

    userid_in_view = userid

    return render(
        request,
        'profilehistory/profile_list.html',
        {
            'profile_list': profile_list,
            'is_userid': is_userid,
            'userid_in_view': userid_in_view,
        }
    )

templates/profilehistory/profile_detail.html
{% extends 'base.html' %}
{% load boards_filter %}

{% block head_title %}
    {{ profile.intro }} - Blog
{% endblock %}

{% block content %}


        <div class="container my-3">
            <div class="row my-3">

                <div class="card mb-3" style="max-width: 540px;">
                  <div class="row g-0">
                      {% if user.is_authenticated%}
                        {% if user == profile.thisuser or user.is_staff or profile.public_approved is True%}
                            <div class="col-md-4">
                                {% if profile.user_image %}
                                  <img src="{{ profile.user_image.url }}" class="img-fluid rounded-start" alt="{{ profile }} userImage">
                                {% else %}
                                    <img src="/static/images/unknown.jpg" class="img-fluid rounded-start" alt="drawn by dalle2 : An oil painting of a humanoid robot playing baduk in the style of Matisse ">
                                {% endif %}
                            </div>
                            <div class="col-md-8">
                              <div class="card-body">
                                <h5 class="card-title">{{ profile.thisuser }}({{ profile.birthdate }})</h5>
                                <p class="card-text"><small class="text-muted">{{ profile.created_at }}</small></p>
                                  <hr/>
                                <p class="card-text">{{ profile.intro }}</p>
                              </div>
                            </div>


                      {% else %}
                            <div class="col-md-4">
                              <img src="/static/images/unknown.jpg" class="img-fluid rounded-start" alt="drawn by dalle2 : An oil painting of a humanoid robot playing baduk in the style of Matisse ">
                            </div>
                            <div class="col-md-8">
                              <div class="card-body">
                                <h5 class="card-title">You know,</h5>
                                <p class="card-text"><small class="text-muted">This is someone else's profile</small></p>
                                  <hr/>
                                <p class="card-text">So, back from here.</p>

                              </div>
                            </div>

                        {% endif %}
                    {% endif %}
                  </div>
                </div>
          </div>
        </div>





{% endblock %}

templates/profilehistory/profile_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load boards_filter %}

{% block head_title %}
    {{ profile.intro }} - Blog
{% endblock %}

{% block content %}

    <h1>Create New Profile</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form | crispy }}
        </table>

        <br/>

        <button type="submit" class="btn btn-success float-end">저장하기</button>
    </form>
    {{ form.media }}

{% endblock %}

templates/profilehistory/profile_list.html
{% extends 'base.html' %}
{% load boards_filter %}
{% block content %}

<div class="container my-3">
    <div class="row my-3">


        {% if is_userid %}
            {% if request.user.is_authenticated%}
                 <div class="col">
                     <h1> {{ userid_in_view }}'s History of Profile </h1>
                 </div>
            {% else %}
                                <div class="col-12 text-center">

                            <span class="display-1 d-block">500</span>
                            <div class="mb-4 lead">웹페이지를 표시할 수 없습니다.</div>
                            <div class="mb-4 lead">Internal Server Error</div>
                            <img class="img-fluid rounded" src="/static/images/logo.png"  alt="logos" width="180" height="85" >
                            <br>
                            <a href="/" class="btn btn-link">홈으로 돌아가기</a>
                        </div>

            {% endif %}
        {% else %}
                {% if request.user.is_authenticated%}
                  <div class="col">
                     <h1> {{ user }}'s History of Profile </h1>
                 </div>
                {% else %}
                        <div class="col-12 text-center">

                            <span class="display-1 d-block">500</span>
                            <div class="mb-4 lead">웹페이지를 표시할 수 없습니다.</div>
                            <div class="mb-4 lead">Internal Server Error</div>
                            <img class="img-fluid rounded" src="/static/images/logo.png"  alt="logos" width="180" height="85" >
                            <br>
                            <a href="/" class="btn btn-link">홈으로 돌아가기</a>
                        </div>
                {% endif %}

                {% if request.user.is_authenticated%}
                <div class="col">

                    <a href="{% url 'profilehistory:profile_create' %}" type="button" class="btn btn-success float-end">프로필 작성하기</a>
                </div>
                <hr/>
                {% else %}
<!--                    <a href="{% url 'common:login' %}" type="button" class="btn btn-success float-end">프로필 작성하기</a> -->
                {% endif %}



        {% endif %}




{% if request.user.is_authenticated%}
        {% if user.is_staff %}
            <table class="table table-striped table-hover">
              <thead class="thead-success">
                <tr>
                  <th scope="col">#번호</th>
                  <th scope="col">제 목</th>
                  <th scope="col">작성일</th>
                </tr>
              </thead>
              <tbody>
         {% else %}
            <table class="table table-striped table-hover">
              <thead class="thead-success">
                <tr>
                  <th scope="col">제 목</th>
                  <th scope="col">작성일</th>
                </tr>
              </thead>
              <tbody>

          {% endif %}
{% endif %}
              {% if profile_list %}
                  {% for p in profile_list %}

              <!--<p>{{p}}/{{ user }}/{{p.thisuser}}</p>-->

                    {% if user.is_authenticated%}
                        {% if user.is_staff %}
                            <tr>
                              <td>#{{p.pk}} -
                                 <a href="{{ p.get_absolute_url }}">
                                    {{p.intro}}
                                  </a>
                              </td>
                              <td>{{p.created_at}} made by {{p.thisuser}}</td>
                                  <td>{% if p.public_approved is True %}
                                        public
                                    {% else %}
                                        private
                                    {% endif %}</td>
                            </tr>
                      {% else %}
                            {% if user == p.thisuser %}
                                <tr>
                                  <td>
                                      <a href="{{ p.get_absolute_url }}">
                                        {{p.intro}}
                                      </a>
                                  </td>
                                  <td>{{p.created_at}}</td>

                                </tr>
                            {% else %}
                              {% if user != p.thisuser %}

                                {% if p.public_approved is True %}
                                    {% if is_userid == True %}
                                    <tr>
                                      <td>
                                       <a href="{{ p.get_absolute_url }}">
                                            {{p.intro}}
                                          </a>
                                      </td>
                                      <td>{{p.created_at}}</td>
                                    </tr>
                                              {% endif %}

                                {% endif %}
                                {% endif %}
                            {% endif %}
                      {% endif %}
                    {% endif %}
                  {% endfor %}
              {% else %}
                <tr>
                    <td>not yet</td>
                    <td>write now</td>
                </tr>
              {% endif %}

              </tbody>
            </table>

    </div>

</div>






{% endblock %}